# Makefile for Mission Incomputable (pebble app component)

all: 
	@echo "Building the Field Agent app..."
	@pebble build

install-emulator:
	@echo "Installing on basalt emulator..."
	@pebble install --emulator basalt --logs

kill:
	@echo "Kill all running emulator instances..."
	@pebble kill

clean:	
	@echo "Cleaning everything..."
	@pebble clean
