# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab2_actually/zybo_master_lab2.xdc

# Block Designs: bd/lab2/lab2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2 || ORIG_REF_NAME==lab2}]

# IP: bd/lab2/ip/lab2_dds_compiler_0_0/lab2_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_dds_compiler_0_0 || ORIG_REF_NAME==lab2_dds_compiler_0_0}]

# IP: bd/lab2/ip/lab2_processing_system7_0_0/lab2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_processing_system7_0_0 || ORIG_REF_NAME==lab2_processing_system7_0_0}]

# IP: bd/lab2/ip/lab2_processing_system7_0_axi_periph_0/lab2_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==lab2_processing_system7_0_axi_periph_0}]

# IP: bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab2_rst_processing_system7_0_100M_0}]

# IP: bd/lab2/ip/lab2_pmod_da2_0_1/lab2_pmod_da2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_pmod_da2_0_1 || ORIG_REF_NAME==lab2_pmod_da2_0_1}]

# IP: bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_axi_gpio_0_0 || ORIG_REF_NAME==lab2_axi_gpio_0_0}]

# IP: bd/lab2/ip/lab2_xbar_0/lab2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xbar_0 || ORIG_REF_NAME==lab2_xbar_0}]

# IP: bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_axi_gpio_0_1 || ORIG_REF_NAME==lab2_axi_gpio_0_1}]

# IP: bd/lab2/ip/lab2_s_axis_mm2s_0_1_1/lab2_s_axis_mm2s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_s_axis_mm2s_0_1 || ORIG_REF_NAME==lab2_s_axis_mm2s_0_1}]

# IP: bd/lab2/ip/lab2_pmod_ad1_0_0/lab2_pmod_ad1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_pmod_ad1_0_0 || ORIG_REF_NAME==lab2_pmod_ad1_0_0}]

# IP: bd/lab2/ip/lab2_DDSclocking_0_1/lab2_DDSclocking_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_DDSclocking_0_1 || ORIG_REF_NAME==lab2_DDSclocking_0_1}]

# IP: bd/lab2/ip/lab2_DDSclocking_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]

# IP: bd/lab2/ip/lab2_cmpy_0_0/lab2_cmpy_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_cmpy_0_0 || ORIG_REF_NAME==lab2_cmpy_0_0}]

# IP: bd/lab2/ip/lab2_xlslice_0_0/lab2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xlslice_0_0 || ORIG_REF_NAME==lab2_xlslice_0_0}]

# IP: bd/lab2/ip/lab2_xlslice_0_1/lab2_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xlslice_0_1 || ORIG_REF_NAME==lab2_xlslice_0_1}]

# IP: bd/lab2/ip/lab2_CIC_0_0/lab2_CIC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_CIC_0_0 || ORIG_REF_NAME==lab2_CIC_0_0}]

# IP: bd/lab2/ip/lab2_CIC_0_1/lab2_CIC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_CIC_0_1 || ORIG_REF_NAME==lab2_CIC_0_1}]

# IP: bd/lab2/ip/lab2_xlconcat_0_0/lab2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xlconcat_0_0 || ORIG_REF_NAME==lab2_xlconcat_0_0}]

# IP: bd/lab2/ip/lab2_xlslice_2_0/lab2_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xlslice_2_0 || ORIG_REF_NAME==lab2_xlslice_2_0}]

# IP: bd/lab2/ip/lab2_xlslice_2_1/lab2_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xlslice_2_1 || ORIG_REF_NAME==lab2_xlslice_2_1}]

# IP: bd/lab2/ip/lab2_xlconcat_1_0/lab2_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_xlconcat_1_0 || ORIG_REF_NAME==lab2_xlconcat_1_0}]

# IP: bd/lab2/ip/lab2_shifter_0_2/lab2_shifter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_shifter_0_2 || ORIG_REF_NAME==lab2_shifter_0_2}]

# IP: bd/lab2/ip/lab2_shifter_0_3/lab2_shifter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_shifter_0_3 || ORIG_REF_NAME==lab2_shifter_0_3}]

# IP: bd/lab2/ip/lab2_downsampler_0_2/lab2_downsampler_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_downsampler_0_2 || ORIG_REF_NAME==lab2_downsampler_0_2}]

# IP: bd/lab2/ip/lab2_downsampler_0_3/lab2_downsampler_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_downsampler_0_3 || ORIG_REF_NAME==lab2_downsampler_0_3}]

# IP: bd/lab2/ip/lab2_FIR_0_0/lab2_FIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_FIR_0_0 || ORIG_REF_NAME==lab2_FIR_0_0}]

# IP: bd/lab2/ip/lab2_FIR_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# IP: bd/lab2/ip/lab2_FIR_0_1/lab2_FIR_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_FIR_0_1 || ORIG_REF_NAME==lab2_FIR_0_1}]

# IP: bd/lab2/ip/lab2_FIR_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# IP: bd/lab2/ip/lab2_demodulator_0_1/lab2_demodulator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_demodulator_0_1 || ORIG_REF_NAME==lab2_demodulator_0_1}]

# IP: bd/lab2/ip/lab2_auto_pc_0/lab2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_auto_pc_0 || ORIG_REF_NAME==lab2_auto_pc_0}]

# XDC: bd/lab2/ip/lab2_dds_compiler_0_0/lab2_dds_compiler_0_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_processing_system7_0_0/lab2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_processing_system7_0_0 || ORIG_REF_NAME==lab2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab2_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab2_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_axi_gpio_0_0 || ORIG_REF_NAME==lab2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_axi_gpio_0_0 || ORIG_REF_NAME==lab2_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab2/ip/lab2_xbar_0/lab2_xbar_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_axi_gpio_0_1 || ORIG_REF_NAME==lab2_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1_ooc.xdc

# XDC: bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab2_axi_gpio_0_1 || ORIG_REF_NAME==lab2_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab2/ip/lab2_DDSclocking_0_1/src/clk_wiz_0/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/lab2/ip/lab2_DDSclocking_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_FIR_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_FIR_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/lab2/ip/lab2_auto_pc_0/lab2_auto_pc_0_ooc.xdc

# XDC: bd/lab2/lab2_ooc.xdc
