# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir O:/ENGS_128/lab6/lab6.cache/wt [current_project]
set_property parent.project_path O:/ENGS_128/lab6/lab6.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths o:/ENGS_128/ENGS128_ip_repo [current_project]
add_files O:/ENGS_128/lab5_with_proc/lab5_with_proc.srcs/sources_1/bd/lab2/ip/lab2_FIR_0_2/src/myROM.coe
add_files O:/ENGS_128/lab5_with_proc/lab5_with_proc.srcs/sources_1/bd/lab2/ip/lab2_FIR_0_3/src/myROM.coe
add_files O:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/lab2.bd
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_dds_compiler_0_0/lab2_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_processing_system7_0_0/lab2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_rst_processing_system7_0_100M_0/lab2_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_axi_gpio_0_0/lab2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_xbar_0/lab2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_axi_gpio_0_1/lab2_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_DDSclocking_0_1/src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_DDSclocking_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_FIR_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_FIR_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all o:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/ip/lab2_auto_pc_0/lab2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all O:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/lab2_ooc.xdc]
set_property is_locked true [get_files O:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/lab2.bd]

read_vhdl -library xil_defaultlib O:/ENGS_128/lab6/lab6.srcs/sources_1/bd/lab2/hdl/lab2_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc O:/ENGS_128/lab6/lab6.srcs/constrs_1/imports/lab2_actually/zybo_master_lab2.xdc
set_property used_in_implementation false [get_files O:/ENGS_128/lab6/lab6.srcs/constrs_1/imports/lab2_actually/zybo_master_lab2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab2_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef lab2_wrapper.dcp

catch { report_utilization -file lab2_wrapper_utilization_synth.rpt -pb lab2_wrapper_utilization_synth.pb }
